admin_form_fill_mails_job:
  cron: "0 18 * * *"
  class: "DeliverAdminFormFillsMailWorker"
  queue: default

allocate_doctors_to_selfies_job:
  cron: "0 */4 * * *"
  class: "AllocateDoctorsToSelfiesWorker"
  queue: default

send_out_selfie_diagnosis_job:
  cron: "0 */2 * * *"
  class: "SendOutSelfieDiagnosisWorker"
  queue: default

send_out_daily_emails_job:
  cron: "0 18 * * *"
  class: "SendOutDailyEmailsWorker"
  queue: default

send_out_daily_sms_job:
  cron: "0 19 * * *"
  class: "SendOutDailySmsWorker"
  queue: default

minify_s3_images_job:
  cron: "30 */2 * * *"
  class: "MinifyImagesWorker"
  queue: default

send_out_doctor_daily_selfie_checkup_stats_job_06:
  cron: "0 6 * * *" # execute every day at  6am for Dr. Asmita
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [7]

send_out_doctor_daily_selfie_checkup_stats_job_09:
  cron: "0 9 * * *" # execute every day at  9am for Dr. Sonam
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [1]

send_out_doctor_daily_selfie_checkup_stats_job_10:
  cron: "0 10 * * *" # execute every day at  10am for Dr. Gaurangi and Dr. Sana
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [2, 8]

send_out_doctor_daily_selfie_checkup_stats_job_19:
  cron: "0 19 * * *" # execute every day at  7pm for Dr. Ankita
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [3]
