admin_form_fill_mails_job:
  cron: "0 18 * * *" # execute at every day 6 p.m.
  class: "DeliverAdminFormFillsMailWorker"
  queue: default

allocate_doctors_to_selfies_job:
  cron: "0 */4 * * *" # execute every 1 hour
  class: "AllocateDoctorsToSelfiesWorker"
  queue: default

send_out_selfie_diagnosis_job:
  cron: "0 */2 * * *" # execute every 2 hours
  class: "SendOutSelfieDiagnosisWorker"
  queue: default

send_out_daily_emails_job:
  cron: "0 18 * * *" # execute every day at 6pm
  class: "SendOutDailyEmailsWorker"
  queue: default

send_out_daily_sms_job:
  cron: "0 19 * * *" # execute every day at 7pm
  class: "SendOutDailySmsWorker"
  queue: default

# update_google_sheets_job:
#   cron: "0 */3 * * *" # execute every 3 hours
#   class: "UpdateSheetsWorker"
#   queue: default

send_out_doctor_daily_selfie_checkup_stats_job_06:
  cron: "0 6 * * *" # execute every day at  6am for Dr. Asmita
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [7]

send_out_doctor_daily_selfie_checkup_stats_job_09:
  cron: "0 9 * * *" # execute every day at  9am for Dr. Sonam
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [1]

send_out_doctor_daily_selfie_checkup_stats_job_10:
  cron: "0 10 * * *" # execute every day at  10am for Dr. Gaurangi and Dr. Sana
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [2, 8]

send_out_doctor_daily_selfie_checkup_stats_job_19:
  cron: "0 19 * * *" # execute every day at  7pm for Dr. Ankita
  class: "SendOutDailySelfieCheckupStatsWorker"
  args: [3]
