# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb36a66e999242a4d8153397fbaace83412de601d9764193f271395f82fa1a1c7bf8716134b70311a158733e88ed9363e371f87052131263dcb6a10b886ddcb
  PAYU_IN_KEY: rjQUPktU
  PAYU_IN_SALT: e5iIg1jwi8
  REMEDICA_PATIENTS_API_KEY: a6kxpBwYXpHRPxHEpKCTWFJlbWVkaWNhIFBhdGllbnRzIENvbnRyb2xsZXI
  PATIENTS_ENDPOINT: http://54.255.145.215/app/api/patient
  #PATIENTS_ENDPOINT: https://remedicohealth.com/app/api/patient
  PAYMENT_URL: https://test.payu.in/_payment
  ADMIN_EMAIL: bh.ranjit@gmail.com
  SENDGRID_USERNAME: bh.ranjit@gmail.com
  SENDGRID_PASS: <%= ENV["SENDGRID_PASS"] %>
  DOMAIN: https://54.255.145.215/consult
  TYPEFORM_API_KEY: <%= ENV["TYPEFORM_API_KEY"] %>
  #PAYTM_MERCHANT_KEY: 1HmXDh!#8ODH7FO6
  #PAYTM_INITIAL_TRASACTION_URL: https://pguat.paytm.com/oltp-web/processTransaction
  #MID: Remedy24705119328083
  #WEBSITE: WEB_STAGING
  #INDUSTRY_TYPE_ID: Retail
  WEBSITE: emedysWEB
  MID : emedys76465438099920
  PAYTM_MERCHANT_KEY:  "&MB7y#@qxLj8G6A@"
  INDUSTRY_TYPE_ID : Retail109
  PAYTM_INITIAL_TRASACTION_URL:  https://secure.paytm.in/oltp-web/processTransaction
  EXOTEL_SID: <%= ENV["EXOTEL_SID"] %>
  EXOTEL_TOKEN: <%= ENV["EXOTEL_TOKEN"] %>
  RAZOR_PAY_KEY_ID: <%= ENV['RAZOR_PAY_KEY_ID'] %>
  RAZOR_PAY_KEY_SECRET: <%= ENV['RAZOR_PAY_KEY_SECRET'] %>
  LE_RAILS_TOKEN: <%= ENV['LE_RAILS_TOKEN'] %>
  AWS_ACCESS_KEY_ID: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  SELFIE_KEY: <%= ENV['SELFIE_KEY'] %>
  DOMAIN_NAME: <%= ENV["DOMAIN_NAME"] %>

test:
  secret_key_base: a2daff293eb0a30a086c526f40d44f68b82c25599c820731164453d9b621f46d0ac11dab14c612a0132a61dc5afb02bf2ea53db91c2ea77d9bdfe53367886dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  WEBSITE: emedysWEB
  MID : <%= ENV["PAYTM_MID"] %>
  PAYTM_MERCHANT_KEY:  "<%= ENV['PAYTM_MERCHANT_KEY'] %>"
  INDUSTRY_TYPE_ID : Retail109
  PAYTM_INITIAL_TRASACTION_URL:  https://secure.paytm.in/oltp-web/processTransaction
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  PAYU_IN_KEY: <%= ENV["PAYU_IN_KEY"] %>
  PAYU_IN_SALT: <%= ENV["PAYU_IN_SALT"] %>
  REMEDICA_PATIENTS_API_KEY: <%= ENV["PATIENTS_API_KEY"] %>
  PATIENTS_ENDPOINT: https://remedicohealth.com/app/api/patient
  PAYMENT_URL: https://secure.payu.in/_payment
  ADMIN_EMAIL: bh.ranjit@gmail.com
  SENDGRID_USERNAME: bh.ranjit@gmail.com
  SENDGRID_PASS: <%= ENV["SENDGRID_PASS"] %>
  DOMAIN: https://remedicohealth.com/consult
  TYPEFORM_API_KEY: <%= ENV["TYPEFORM_API_KEY"] %>
  EXOTEL_SID: <%= ENV["EXOTEL_SID"] %>
  EXOTEL_TOKEN: <%= ENV["EXOTEL_TOKEN"] %>
  RAZOR_PAY_KEY_ID: <%= ENV['RAZOR_PAY_KEY_ID'] %>
  RAZOR_PAY_KEY_SECRET: <%= ENV['RAZOR_PAY_KEY_SECRET'] %>
  LE_RAILS_TOKEN: <%= ENV['LE_RAILS_TOKEN'] %>
  AWS_ACCESS_KEY_ID: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  SELFIE_KEY: <%= ENV['SELFIE_KEY'] %>
  DOMAIN_NAME: <%= ENV["DOMAIN_NAME"] %>
